sudo: false
language: node_js
node_js:
  - iojs
  - '0.10'
  - '0.12'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-npmodule' ]; then cd .. && eval "mv $currentfolder generator-npmodule" && cd generator-npmodule; fi

